### ISSUE TITLE
Create NextJS proof of concept

### ISSUE THREAD

**Issue by ryankeairns** [elastic/design-system-team#167]
Prove the validity of a NextJS/Markdown authoring platform for use as a new, expanded EUI documentation site.
Expand IA and test authoring environment with new contributors across the UX organization.

**Comment by ryankeairns** [comment]
Live PoC: https://eui-plus.vercel.app/

@miukimiu for the sake of history and completeness, please briefly summarize your findings.
If there is no other outstanding work, then we can close this issue and consider the PoC done.

Thanks and great work on this. It generated a lot of interested and validated the need for more robust design system documentation set in a simpler authoring environment.

**Comment by miukimiu** [comment]
Updates are up (https://eui-plus.vercel.app) and the PoC is done.

We can still use the prototype for testing new things like DemoJS tabs, side nav, and some guidelines.

### Findings

- One of the things I wanted to test with the prototype was the use of `MDX` with content writers and designers. It went well
- I also tested how blog posts can work. 
- It was an interesting exercise in helping to define the IA. The initial IA has 3 different sections "build", "design" and "writers" and it didn't work out. The content seemed very disconnected. So the prototype was updated to reflect the new IA.
- We need to establish best practices for writing guidelines. Several contributions showed that guidelines had different formats and different usage of components. 
- We need better-formatting helpers to support contributors. Participants expressed a desire to see more interactive examples instead of static images.
